version: '3.3'

services:
  nginx:
    image:
      nginx:1.13.5
    container_name: nginx-er
    # restart: always
    ports:
      - 7755:80
      - 443:443
    volumes:
      - ./src:/code
      - ./.dockers/nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
      - ./.dockers/nginx/conf/projects:/etc/nginx/conf.d/projects
      - ./.dockers/nginx/conf/fsg:/etc/nginx/conf.d/fsg
      - ./dockers/docker-data/nginx:/var/log/nginx/
    networks:
      - code-network
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./.dockers/php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm-er
    # restart: always
    depends_on:
#      - syslog
#      - mailer
      - postgres
    volumes:
      - ./src:/code
      - ./.dockers/php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - code-network

  redis:
    image: redis:3.2
    container_name: redis-er
    # restart: always
    command: redis-server --requirepass ucG3S!HP0
    volumes:
    - ./dockers/docker-data/redis-data/tmp:/tmp
    - ./dockers/docker-data/redis-data:/var/lib/redis
    - ./.dockers/redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
    - 6381:6379
    networks:
    - code-network

  postgres:
    image: postgres:9.6
    container_name: postgres-er
    # restart: always
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: '123123'
      POSTGRES_DB: 'geektown'
    ports:
        - "13333:5432"
    volumes:
      - ./dockers/docker-data/postgresql:/var/lib/postgresql
      - ./dockers/docker-data/postgresql_data:/var/lib/postgresql/data
    networks:
      - code-network


networks:
  code-network:
    driver: bridge

